config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :users

  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'
end

app/models/room.rb
class Room < ActiveRecord::Base

	validates_presence_of :title, :location, :description
	validates_length_of :description, minimum: 30, allow_blank: false
	
	def complete_name
		"#{title}, #{location}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEX = /\A[^@]+@([^@\.]+\.)+[^@\.]+\Z/

	scope :confirmed, -> { where.not(confirmed_at: nil) }
	
	validates_format_of :email, with: EMAIL_REGEX
	validates_presence_of :email, :full_name, :location
	validates_length_of :bio, minimum: 30, allow_blank: false
	validates_uniqueness_of :email

	has_secure_password

	before_create do |user|
		user.confirmation_token = SecureRandom.urlsafe_base64
	end
	def confirm!
		return if confirmed?
		
		self.confirmed_at = Time.current
		self.confirmation_token = ''
		save!
	end

	def confirmed?
		confirmed_at.present?
	end

	def self.authenticate(email, password)
		user = confirmed.find_by(email: email)
		if user.present?
			user.authenticate(password)
		end
	end
end

app/models/user_session.rb
class UserSession
	include ActiveModel::Model

	attr_accessor :email, :password
	validates_presence_of :email, :password

	def initialize(session, attributes={})
		@session = session
		@email = attributes[:email]
		@password = attributes[:password]
	end

	def authenticate!
		user = User.authenticate(@email, @password)

		if user.present?
			store(user)
		else
			errors.add(:base, :invalid_login)
			false
		end
	end
	def store(user)
		@session[:user_id] = user.id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
	def show
		user = User.find_by(confirmation_token: params[:token])

		if user.present?
			user.confirm!
			redirect_to user, notice: 'Successfully confirmed!'
		else
			redirect_to root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@rooms = Room.take(3)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

 def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room,
      notice: 'Successfully registered!'
    else
      render action: :new
    end
  end

  def update
    set_room

    if @room.update(room_params)
      redirect_to @room, notice: 'Succesfully changed!'
    else
      render action: :edit    
    end 
    
  end

  def destroy
      set_room
      @room.destroy
      redirect_to @room,
      notice: 'Succesfully deleted!'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	def new
		@user_session = UserSession.new(session)
	end

	def create
		@user_session = UserSession.new(session, params[:user_session])
		if @user_session.authenticate!
			redirect_to root_path, notice: 'Succesfully Signed in'
		else
			render :new
		end
	end

	def destroy
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		set_user
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			Signup.confirm_email(@user).deliver

			redirect_to @user, notice: 'Successfully registered!'
		else
			render action: :new
		end
	end

	def edit
		set_user
	end

	def update
		set_user

		if @user.update(user_params)
			redirect_to @user,
			notice: 'Succesfully changed!'
		else
			render action: :edit		
		end	
	end

	def destroy
		set_user
	    @user.destroy
	    redirect_to @user,
			notice: 'Succesfully deleted!'
 	end

 	private
 	def set_user
 		@user = User.find(params[:id])
 	end

	private
	def user_params
		params.
			require(:user).
			permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(
				:div,
				model.errors[attribute].first,
				class: 'error_message danger-color'	
			)
		end
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<div class="container">
	<% if notice %>
		<div class="alert alert-warning" role="alert">
			<p class="notice"><%= notice %></p>
		</div>
	<% end %>

	<h2>Recently Posted Rooms</h2>
	<ul>
		<% @rooms.each do |room| %>
			<%= link_to room.complete_name, room %>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Colchonet</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
		   <div class="navbar-header">
		    	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false"> 
			    	<span class="sr-only">Toggle navigation</span>
			     	<span class="icon-bar"></span> 
			     	<span class="icon-bar"></span>
			      	<span class="icon-bar"></span> 
		      </button> 
		      <%= link_to 'Colcho.net', root_path ,class: "navbar-brand" %>
		    </div> 
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
		    	<ul class="nav navbar-nav"> 
		        	<li><%= link_to 'Home', root_path %></li>
		         	<li><%= link_to "Users",users_path %></li> 
		         	<li><%= link_to "Rooms", rooms_path %></li>
		         </ul>
		    </div>
	   	</div> 
	</nav>
		<%= yield %>
	</body>
</html>

app/views/rooms/_form.html.erb
<% if @room.errors.any? %>
  <div id="error_explanation">
    <h3>there are errors in this form, please check it</h3>
    <br />
  </div>
<% end %>

<%= form_for @room do |f| %>
  <div class="row">
    <div class="col-md-4">
         <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "form-control" %>
          <%= error_tag @room, :title %>
        </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :location %> <br />
        <%= f.text_field :location, class: "form-control" %>
        <%= error_tag @room, :location %>
      </div>
    </div>
   </div> 
   
   <div class="row">
    <div class="col-md-4">
      <div class="form-group">
         <%= f.label :description %><br>
         <%= f.text_area :description, class: "form-control" %>
         <%= error_tag @room, :description %>
      </div>
    </div>
   </div>
  
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
	<h1>Editing Room</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @room %> |
	<%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Listing Rooms</h1>
  
  <% if @rooms.size > 0  %>
    <table class="table">
     <thead> 
      <tr> 
        <th>Title</th>
        <th>Location</th>
        <th>Description</th>
      </tr> 
      </thead> 
      <tbody>
       <% @rooms.each do |room| %>
          <tr>
            <td><%= room.title %></td>
            <td><%= room.location %></td>
            <td><%= truncate(room.description, :length => 35) %></td>
            <td><%= link_to 'Show', room %></td>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <% else %>
          <div class="alert alert-info" role="alert">nothing to Show</div>
   <% end %>

   <%= link_to 'New Room', new_room_path %>
</div>

app/views/rooms/new.html.erb
<div class="container">
	<h1>New Room</h1>

	<%= render 'form' %>

	<%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<div class="container">
	<div class="container">
	<% if notice %>
		<div class="alert alert-warning" role="alert">
			<p class="notice"><%= notice %></p>
		</div>
	<% end %>
	<div class="row">
		<div>
			<h2 class="text-center">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
				<%= @room.title %>
			</h2>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<div class="list-group">
			  <a href="#" class="list-group-item active">
			    <strong>Title:</strong> <%= @room.title %>
			  </a>
			  <a href="#" class="list-group-item">
			  	<strong>Location:</strong> <%= @room.location %>
			  </a>
			  <a href="#" class="list-group-item">
			  	<strong>Description:</strong> <%= truncate(@room.description, :length => 60) %>
			  </a>
			</div>
		</div>
	</div>
</div>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/signup/confirm_email.html.erb
<h1><%= t("Seja bem vindo ao Colcho.net !") %></h1>

<p>
	<%= t("Seja bem vico ao Colcho.net, #{@user.full_name}!") %>
</p>
<p>
	<%= t("O Colcho.net e o lugar ideal par voce alugar aquele quarto sobrando na sua casa e ainda conhecer muita gente do mundo inteiro.") %>
</p>
<p>
	<%= t ('Para comecar a usar o site acesse o link: ') %>
	<%= link_to(@confirmation_link, @confirmation_link) %>
</p>

<p>
	<%= t ('Obrigado por se cadastrar no: ') %>
	<%= link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t("Seja bem vico ao Colcho net, #{@user.full_name}!") %>
<%= t("O Colcho net e o lugar ideal par voce alugar aquele quarto sobrando na sua casa e ainda conhecer muita gente do mundo inteiro.") %>
<%= t ('Para comecar a usar o site acesse o link: ') %>
<%= link_to(@confirmation_link, @confirmation_link) %>
<%= t ('Obrigado por se cadastrar no: ') %>
<%= link_to('Colcho.net', root_url) %>
<%= link_to 'Back', root_url %>

app/views/user_sessions/new.html.erb
<div class="container">
	<% if @user_session.errors.any? %>
	  <div id="error_explanation">
	    <h3>there are errors here, please check it</h3>
	    <br />
	  </div>
	<% end %>

	<%= form_for @user_session do |f| %>
		<p>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= error_tag @user_session, :email %>
		</p>
		<p>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= error_tag @user_session, :password %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
	<p><%= link_to t('.sign_up'),new_user_path %></p>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>there are errors in this form, please check it</h2>
		<br />
	</div>
<% end %>

<%= form_for @user do |f| %>
	<div class="row">
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :full_name %> <br />
				<%= f.text_field :full_name, class: "form-control" %>
				<%= error_tag @user, :full_name %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :location %> <br />
				<%= f.text_field :location, class: "form-control" %>
				<%= error_tag @user, :location %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :email %> <br />
				<%= f.text_field :email, class: "form-control" %>
				<%= error_tag @user, :email %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :password %> <br />
				<%= f.password_field :password, class: "form-control" %>
				<%= error_tag @user, :password %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :password_confirmation %> <br />
				<%= f.password_field :password_confirmation, class: "form-control" %>
				<%= error_tag @user, :password_confirmation %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :bio %> <br />
				<%= f.text_area :bio, class: "form-control" %>
				<%= error_tag @user, :bio %>
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit user</h1>

	<%= render 'form' %>
	<%= link_to 'Voltar ao perfil', @user %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Listing Users</h1>
  
  <% if @users.size >0  %>
    <table class="table">
     <thead> 
      <tr> 
        <th>Full Name</th>
        <th>Location</th>
        <th>Email</th> 
        <th>Bio</th>
      </tr> 
    </thead> 
    <tbody>
      <% @users.each do |user| %>
        <tr>

          <td><%= user.full_name %></td>
          <td><%= user.location %></td>
          <td><%= user.email %></td>
          <td><%= truncate(user.bio, :length => 35) %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
          <div class="alert alert-info" role="alert">nothing to Show</div>
   <% end %>
      
  <%= link_to 'New User', new_user_path, :class=>"btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New user</h1> <br />
	<%= render 'form' %>
	<%= link_to 'Voltar', rooms_path %>
</div>

app/views/users/show.html.erb
<div class="container">
	<% if notice %>
		<div class="alert alert-warning" role="alert">
			<p class="notice"><%= notice %></p>
		</div>
	<% end %>
	<div class="row">
		<div>
			<h2 class="text-center">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
				<%= @user.full_name %>
			</h2>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<div class="list-group">
			  <a href="#" class="list-group-item active">
			    <strong>Name:</strong> <%= @user.full_name %>
			  </a>
			  <a href="#" class="list-group-item">
			  	<strong>Location:</strong> <%= @user.location %>
			  </a>
			  <a href="#" class="list-group-item">
			  	<strong>Bio:</strong> <%= truncate(@user.bio, :length => 60) %>
			  </a>
			</div>
		</div>
	</div>
</div>
<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>